### ISSUE TITLE
How to uninstall flyctl

### ISSUE THREAD

**Issue by yodaheYT** [superfly/docs#312] opened 2022-09-02 22:28 UTC
Hello on my quest to migrate my app from Heroku, I found fly.io. But once I looked into it, its not what I need. I installed from the powershell script, how do I uninstall flyctl from my system?
Maybe add uninstall instructions to docs.

**Comment by yeskunall** [comment] 2022-11-28 09:13
@yodaheYT no official docs for this yet AFAICT. See if #173 helps.

**Comment by catflydotio** [comment] 2023-01-12 20:59
Dupe of https://github.com/superfly/docs/issues/173

**Closed by catflydotio** 2023-01-12 20:59 UTC
